<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6KOFRV4" failures="1" tests="3" name="mobileApp.BillGenrator.UtilityBill" time="112.527" errors="0" timestamp="2023-01-03T19:19:08 IST" skipped="0">
  <testcase classname="mobileApp.BillGenrator.UtilityBill" name="UtilityForm_VerifyUtilityPreviewWithAllFields" time="100.732"/>
  <system-out/>
  <testcase classname="mobileApp.BillGenrator.UtilityBill" name="UtilityForm_verifyDataOfUtilityOrderPage" time="4.721"/>
  <system-out/>
  <testcase classname="mobileApp.BillGenrator.UtilityBill" name="UtilityForm_verifyCouponCodeFunctionalityWithValidCode" time="7.074">
    <failure message="The following asserts failed:
	Coupon not applied expected [ $ 0.0] but found [$ 20.0],
	Text on checkout button does not change after applying free coupen expected [Complete Checkout] but found [Pay With Crypto]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Coupon not applied expected [ $ 0.0] but found [$ 20.0],
Text on checkout button does not change after applying free coupen expected [Complete Checkout] but found [Pay With Crypto]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at mobileApp.BillGenrator.UtilityBill.UtilityForm_verifyCouponCodeFunctionalityWithValidCode(UtilityBill.java:195)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UtilityForm_verifyCouponCodeFunctionalityWithValidCode -->
  <system-out/>
</testsuite> <!-- mobileApp.BillGenrator.UtilityBill -->
